name: Build and deploy the website
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  website:
    uses: ./.github/workflows/deploy-stage.yml
    with:
      service: website
      context: root-site
      app: thomasriley-blog-w3-pilot
