name: lint
on: [workflow_dispatch, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies for root-site
        run: |
          cd root-site
          npm ci
      - name: Run lint on root-site
        run: |
          cd root-site
          npm run lint
      - name: Install dependencies for article-service
        run: |
          cd article-service
          npm ci
      - name: Run lint on article-service
        run: |
          cd article-service
          npm run lint
